#!/usr/bin/env bash

opt_debug=false

while getopts :dh opt
do
	case "$opt" in
		d) opt_debug=true;;
		h) echo "usage: $0 [-d] [progenitor]"; exit 0;;
	esac
done

shift $((OPTIND - 1))

if test $# -eq 1
then progenitor="$1"
else progenitor="$(find data -mindepth 2 -type d | fzf -d / --with-nth 2..)"
fi

test -d "$progenitor" || {
	echo "$0: error: non-directory argument" >&2
	exit 1
}

inspect() {
	if $opt_debug
	then vipe
	else cat
	fi
}

mkdir -p deliverables

bash scripts/jaywalk \
               -b .image:node_g.jpg \
               -B .partners[%u].image:node_p%u.jpg \
                       "$progenitor" bio.json |
	jq -rf scripts/treeify |
	inspect > deliverables/tree.tex &&
	latexmk -pdf -cd deliverables/tree.tex &&
	latexmk -c   -cd deliverables/tree.tex

# TODO possibly compile over standard input using pdflatex instead of latexmk

# NOTE that if the debug flag is passed and the environment variable EDITOR is
# set to vim, then the user can exit the pipeline prematurely by typing
# `:cq<Enter>`.  This is useful if the jq script fails (as indicated by empty
# output into vipe) and the error message must be seen before being scrolled
# away by LaTeX output.
