#!/usr/bin/env bash

opt_debug=false

while getopts :d opt
do
	case "$opt" in
		d) opt_debug=true;;
	esac
done

inspect() {
	if $opt_debug
	then vipe
	else cat
	fi
}

progenitor=$(find data -mindepth 2 -type d | fzf -d / --with-nth 2..)

mkdir -p deliverables

bash scripts/jaywalk $progenitor bio.json |
	jq -rf scripts/treeify |
	inspect > deliverables/tree.tex &&
	latexmk -pdf -cd deliverables/tree.tex &&
	latexmk -c   -cd deliverables/tree.tex

# NOTE that if the debug flag is passed and the environment variable EDITOR is
# set to vim, then the user can exit the pipeline prematurely by typing
# `:cq<Enter>`.  This is useful if the jq script fails (as indicated by empty
# output into vipe) and the error message must be seen before being scrolled
# away by LaTeX output.
