#!/usr/bin/env bash

# FILENAME: jaywalk
# AUTHOR: Zachary Krepelka
# DATE: Monday, August 11th, 2025
# ABOUT: recursive json file accumulator
# ORIGIN: https://github.com/zachary-krepelka/genealogy.git
# UPDATED: Monday, July 27th, 2026 at 5:21 PM

# Functions --------------------------------------------------------------- {{{1

program="${0##*/}"

usage() {
	local message

	IFS= read -r -d '' message <<-EOF || true
	Recursive JSON File Accumulator

	Usage:
	  bash $program [-hH] [-k <key>] [-a <k:v>]... <dir> <filename>

	Options:
	  -k <key>             change name of [k]ey under which objects are nested
	  -a <field:filename>  [a]ppend file resource to each object if present

	Documentation:
	  -h  display this [h]elp message and exit
	  -H  read documentation for this script then exit
	EOF
	printf '%s' "$message"
}

documentation() {
	pod2text "$0" | less -Sp '^[^ ].*$' +k
}

error() {
	local code="$1" message="$2"
	echo "$program: error: $message" >&2
	exit "$code"
}

warn() {
	local message="$1"
	echo "$program: warning: $message" >&2
}

check_dependencies() {

	local dependencies=(find jq less pod2text realpath wc)

	local cmd missing= code="$1"

	for cmd in "${dependencies[@]}"
	do
		if ! command -v "$cmd" &>/dev/null
		then missing+="$cmd, "
		fi
	done

	if test -n "$missing"
	then error "$code" "missing dependencies: ${missing%, }"
	fi
}

walk() {
	local directory="$1"

	if has_children "$directory"
	then
		jq -s ".[0] + {\"$key\": .[1:]}" \
			<(get_json "$directory") \
			<(get_children "$directory")
	else
		get_json "$directory"
	fi
}

get_json() {
	local directory="$1" filter= resource_{field,file,path}

	if $opt_append
	then
		eval "$serialized_resources"

		for resource_field in "${!resources[@]}"
		do
			resource_file="${resources[$resource_field]}"
			resource_path="$directory/$resource_file"

			if test -f "$resource_path"
			then
				resource_path="$(realpath "$resource_path")"
				filter+="$resource_field = \"$resource_path\" | "
			fi
		done

		filter="${filter% | }"
	fi

	test -z "$filter" && filter=.

	jq "$filter" "$directory/$target"
}

has_children() {
	test $(find "$1" -mindepth 1 -maxdepth 1 -type d | wc -l) -ne 0
}

get_children() {
	find "$1" -mindepth 1 -maxdepth 1 -type d -exec bash -c "walk '{}'" \;
}

# Command-line Option Parsing --------------------------------------------- {{{1

declare opt_{help,doc,append,invalid}=false

declare -A resources

key=children

while getopts ':a:hHk:' opt
do
	case "$opt" in
		a) opt_append=true; resources["${OPTARG%:*}"]="${OPTARG##*:}";;
		h) opt_help=true;;
		H) opt_doc=true;;
		k) key="$OPTARG";;
		*) opt_invalid=true; invalid_opt+="$OPTARG";;
	esac
done

shift $((OPTIND - 1))

# Option Handling --------------------------------------------------------- {{{1

# Options are handled after they are parsed to enforce a consistent
# order of evaluation. If options were handled in the getopts loop as
# they are parsed, the order of evaluation would depend on the order
# that the user passed the options.

if $opt_help
then
	usage # does not use external commands
	exit 0
fi

check_dependencies 1 # must be called before any external command

if $opt_doc
then
	documentation # uses external commands
	exit 0
fi

if $opt_invalid
then
	warn "unknown options: -$invalid_opt"
fi

# Argument Handling ------------------------------------------------------- {{{1

if test $# -ne 2
then error 2 'exactly two arguments are required'
fi

path="${1%/}" target="$2"

if ! test -d "$path"
then error 3 '<path> is not a directory'
fi

# Main Processing --------------------------------------------------------- {{{1

export key target opt_append serialized_resources=$(declare -p resources)

export -f walk get_json {has,get}_children

walk "$path" || error 4 "Something went wrong. You're on your own. Good Luck."

# Documentation ----------------------------------------------------------- {{{1

: <<='cut'
=pod

=head1 NAME

jaywalk - recursive json file accumulator

=head1 SYNOPSIS

 bash jaywalk [-hH] [-k <key>] [-a <k:v>]... <dir> <filename>

=head1 DESCRIPTION

This program accumulates JSON files dispersed throughout a directory
structure into a single, nested JSON object.  Every subdirectory of
<dir> should contain a JSON file whose filename is <filename>.

My motivation in writing this script was to ease the process of editing
a nested json file.  Rather than editing one large file, I can edit
individual files while using shell commands to traverse the directory
structure.  Thereafter, the individual files may be assembled into one
large file with the hierarchical relationship preserved.

=head1 OPTIONS

=over

=item B<-h>

Display a [h]elp message and exit.

=item B<-H>

Display this documentation in a pager and exit after the user quits.
The documentation is divided into sections.  Each section header is
matched with a search pattern, meaning that you can use navigation
commands like C<n> and its counterpart C<N> to go to the next or
previous section respectively.

=item B<-k> I<KEY>

This option changes the name of the [k]ey under which objects are
nested. The default key is C<children>.

=item B<-a> I<FIELD>:I<FILENAME>

This option [a]ppends a unique file resource I<FILENAME> to each JSON
object as I<FIELD> if it is present.  That is, for each JSON file X, if
I<FILENAME> exists in the same directory as X, then append the path of
I<FILENAME> as a string under the key I<FIELD> of X before it is
assimilated into the nested JSON structure.  Note that I<FIELD> is a jq
path expression and therefore must begin wtih a dot, e.g.,
C<.foo.bar.baz>.  Here is an example in context.

 bash jaywalk -a .image:portrait.jpg family-tree/ person.json

This option is cumulative and can be specified multiple times. Each
unique I<FIELD> inserts a new file resource. If a duplicate I<FIELD> is
provided, the last specified I<FILENAME> overwrites prior entries for
that I<FIELD>.

=back

=head1 EXAMPLES

Consider the following directory structure.

 Skywalker/
 `-- Anakin/
     |-- bio.json
     |    [ {
     |    [   "name": "Anakin Skywalker"
     |    [ }
     |-- Leia/
     |   |-- bio.json
     |   |    [ {
     |   |    [   "name": "Leia Skywalker"
     |   |    [ }
     |   `-- Ben/
     |       `-- bio.json
     |            [ {
     |            [   "name": "Ben Solo"
     |            [ }
     `-- Luke/
         `-- bio.json
              [ {
              [   "name": "Luke Skywalker"
              [ }

 5 directories, 4 files

Run the program with the following arguments.

 bash jaywalk Skywalker/Anakin bio.json

This gives the following.

 {
   "name": "Anakin Skywalker",
   "children": [
     {
       "name": "Leia Skywalker",
       "children": [
         {
           "name": "Ben Solo"
         }
       ]
     },
     {
       "name": "Luke Skywalker"
     }
   ]
 }

This is easily parsed using the command-line JSON processor C<jq>.

 bash jaywalk Skywalker/Anakin bio.json | jq -r 'recurse(.children[]?).name'

This gives the following.

 Anakin Skywalker
 Leia Skywalker
 Ben Solo
 Luke Skywalker

=head1 DIAGNOSTICS

The program exits with the following status codes.

=over

=item 0 if okay

=item 1 if dependencies are missing

=item 2 if the wrong number of positional arguments are passed

=item 3 if the first positional argument is not a directory

=item 4 for some other unforeseen error

=back

=head1 NOTES

The name of this program is a portmanteau of the words I<JSON> and
I<walk> with the I<J> in I<JSON> stressed as I<jay>.  It is a pun on the
crime of jaywalking.  A friend of mine had commented that nesting
folders deeply is cumbersome, remarking how much assembly code is
involved.  To that end, the use of this script is jokingly a crime.

=head1 AUTHOR

Zachary Krepelka L<https://github.com/zachary-krepelka>

=cut
